QtCharts: fix GCC 13-detected dangling element reference warning
QColorAxis::gradient() returns a QLinearGradient by value,
QGradient::stops() returns a QList<QGradientStop> by value, so storing
the reference returned by QList::operator[] is, strictly speaking,
dangling. In practice, it isn't because QList is COW and thus the
element is not going to be destroyed, but let's not depend on that
detail.

chartaxiselement.cpp:437:33: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
chartaxiselement.cpp:437:71: note: the temporary was destroyed at the end of the full expression ‘QGradient::stops() const().QList<std::pair<double, QColor> >::operator[](((qsizetype)i))’

Pick-to: 6.5
Change-Id: Ide4dbd0777a44ed0870efffd1739488e1958f814
Reviewed-by: Miikka Heikkinen <miikka.heikkinen@qt.io>